/*
 * Decompiled with CFR 0_110.
 * 
 * Could not load the following classes:
 *  java.lang.Integer
 *  java.lang.Object
 *  java.lang.String
 */
package com.androidvideoplayer;

public class Constants {
    public static final int ANIM_DURATION = 10000;
    public static String BHAJANS;
    public static String BOL_INVITE_ALL_TO_BE_CALLED;
    public static String BOL_IS_DEVICE_XIAOMI;
    public static String BOL_IS_SONG_TO_BE_REPEATED;
    public static String BOOL_JSON_DATA;
    public static int CONN_TIMEOUT = 0;
    public static String DATA_URL;
    public static final int EMPTY_MESSAGE_WHAT = 1;
    public static String GOD_EIGHT;
    public static String GOD_EIGHT_DESCRIPTION_LONG_DESC;
    public static int GOD_EIGHT_IMAGE = 0;
    public static Integer[] GOD_EIGHT_IMAGES;
    public static String GOD_FIVE;
    public static String GOD_FIVE_DESCRIPTION_LONG_DESC;
    public static String GOD_FIVE_DESCRIPTION_SHORT_DESC;
    public static int GOD_FIVE_IMAGE = 0;
    public static Integer[] GOD_FIVE_IMAGES;
    public static String GOD_FOUR;
    public static String GOD_FOUR_DESCRIPTION_LONG_DESC;
    public static String GOD_FOUR_DESCRIPTION_SHORT_DESC;
    public static int GOD_FOUR_IMAGE = 0;
    public static Integer[] GOD_FOUR_IMAGES;
    public static String GOD_ONE;
    public static String GOD_ONE_DESCRIPTION_LONG_DESC;
    public static String GOD_ONE_DESCRIPTION_SHORT_DESC;
    public static int GOD_ONE_IMAGE = 0;
    public static Integer[] GOD_ONE_IMAGES;
    public static String GOD_SEVEN;
    public static String GOD_SEVEN_DESCRIPTION_LONG_DESC;
    public static int GOD_SEVEN_IMAGE = 0;
    public static Integer[] GOD_SEVEN_IMAGES;
    public static String GOD_SIX;
    public static String GOD_SIX_DESCRIPTION_LONG_DESC;
    public static String GOD_SIX_DESCRIPTION_SHORT_DESC;
    public static int GOD_SIX_IMAGE = 0;
    public static Integer[] GOD_SIX_IMAGES;
    public static String GOD_THREE;
    public static String GOD_THREE_DESCRIPTION_LONG_DESC;
    public static String GOD_THREE_DESCRIPTION_SHORT_DESC;
    public static int GOD_THREE_IMAGE = 0;
    public static Integer[] GOD_THREE_IMAGES;
    public static String GOD_TO_SELECT;
    public static String GOD_TWO;
    public static String GOD_TWO_DESCRIPTION_LONG_DESC;
    public static String GOD_TWO_DESCRIPTION_SHORT_DESC;
    public static int GOD_TWO_IMAGE = 0;
    public static Integer[] GOD_TWO_IMAGES;
    public static String INT_CREDITS_NUMBER;
    public static String INT_CURRENT_GOD_IMAGE_POSITION;
    public static boolean IS_JSON_FILE_DOWNLOADED = false;
    public static String KEERTHANS;
    public static final int MAX_DELAY = 6000;
    public static String M_MSG;
    public static int NOTIFICATION_SHORT_DESCRIPTION_TIMEOUT;
    public static int NOTIFICATION_TIMEOUT;
    public static String PLAY_LINK;
    public static int SAMPLING_SIZE;
    public static int SAMPLING_SIZE_GRID;
    public static String SHARED_PREFERENCE_NAME;
    public static String SLOKHAS;
    public static String SONG_TO_SELECT;
    public static int SPLASH_TIME;
    public static String STR_CURRENT_GOD_SONG_POSITION;
    public static String STR_GOD_CATEGORY;
    public static String STR_GOD_HOME_ARRAY_NO;
    public static String STR_GOD_IMAGE;
    public static String STR_GOD_IMAGE_SELECTED;
    public static String STR_GOD_NAME;
    public static String STR_GOD_REFERENCE_SONG;
    public static String STR_GOD_SELECTED;
    public static String STR_IS_FAV_GOD_SELECTED_BOOL;
    public static String STR_IS_FAV_SONG_SELECTED;
    public static String STR_IS_LOG_FILE_PRESENT;
    public static String STR_JSON_DATA;
    public static String STR_LOG_FILE;
    public static String STR_SONG_NAME;
    public static String STR_SONG_SELECTED;
    public static String STR_VERSION_NO;

    static {
        DATA_URL = "http://www.godiswithme.in/Mp3SongsImagesMetadata22.json";
        M_MSG = "I experienced God is with Me App and it is really good. So I decided to recommend it to you as well. Please install it from https://play.google.com/store/apps/details?id=com.twinvave.godiswithme and get lot of God's blessings. Thank you";
        SHARED_PREFERENCE_NAME = "MyPref";
        IS_JSON_FILE_DOWNLOADED = false;
        GOD_TO_SELECT = "godToSelect";
        SONG_TO_SELECT = "songToSelect";
        BOOL_JSON_DATA = "";
        STR_JSON_DATA = "data";
        STR_GOD_SELECTED = "godSelected";
        STR_SONG_SELECTED = "songSelected";
        STR_VERSION_NO = "versionNo";
        STR_GOD_IMAGE_SELECTED = "godImgSelected";
        STR_GOD_HOME_ARRAY_NO = "godArrNo";
        INT_CREDITS_NUMBER = "godCredits";
        BOL_INVITE_ALL_TO_BE_CALLED = "inviteAllToBECalled";
        BOL_IS_SONG_TO_BE_REPEATED = "isSongToBeRepeated";
        BOL_IS_DEVICE_XIAOMI = "isXiaomi";
        STR_IS_FAV_GOD_SELECTED_BOOL = "isFavGodSel";
        INT_CURRENT_GOD_IMAGE_POSITION = "godCurrentImagePosition";
        STR_GOD_NAME = "godName";
        STR_LOG_FILE = "logFile";
        STR_IS_LOG_FILE_PRESENT = "isLogFilePresent";
        STR_SONG_NAME = "songName";
        STR_IS_FAV_SONG_SELECTED = "isFavSongSel";
        STR_GOD_IMAGE = "godImage";
        STR_GOD_CATEGORY = "godCategory";
        STR_GOD_REFERENCE_SONG = "godReferenceSong";
        STR_CURRENT_GOD_SONG_POSITION = "godCurrentSongPosition";
        NOTIFICATION_TIMEOUT = 5000;
        NOTIFICATION_SHORT_DESCRIPTION_TIMEOUT = 10000;
        SPLASH_TIME = 3000;
        SAMPLING_SIZE = 4;
        SAMPLING_SIZE_GRID = 8;
        CONN_TIMEOUT = 10000;
        GOD_ONE = "Shiva";
        GOD_TWO = "Ganesha";
        GOD_THREE = "Vishnu";
        GOD_FOUR = "Durga";
        GOD_FIVE = "Lakshmi";
        GOD_SIX = "ShirdiSaiBaba";
        GOD_SEVEN = "SriKrishna";
        GOD_EIGHT = "Ayyappa";
        BHAJANS = "bhajan";
        KEERTHANS = "stotram";
        SLOKHAS = "stuti";
        GOD_ONE_IMAGE = 2130837624;
        GOD_TWO_IMAGE = 2130837579;
        GOD_THREE_IMAGE = 2130837632;
        GOD_FOUR_IMAGE = 2130837574;
        GOD_FIVE_IMAGE = 2130837595;
        GOD_SIX_IMAGE = 2130837610;
        GOD_SEVEN_IMAGE = 2130837592;
        GOD_EIGHT_IMAGE = 2130837555;
        Integer[] arrinteger = new Integer[]{2130837624, 2130837626, 2130837625};
        GOD_ONE_IMAGES = arrinteger;
        Integer[] arrinteger2 = new Integer[]{2130837579, 2130837581, 2130837580};
        GOD_TWO_IMAGES = arrinteger2;
        Integer[] arrinteger3 = new Integer[]{2130837632, 2130837634, 2130837633};
        GOD_THREE_IMAGES = arrinteger3;
        Integer[] arrinteger4 = new Integer[]{2130837574, 2130837576, 2130837575};
        GOD_FOUR_IMAGES = arrinteger4;
        Integer[] arrinteger5 = new Integer[]{2130837595, 2130837597, 2130837596};
        GOD_FIVE_IMAGES = arrinteger5;
        Integer[] arrinteger6 = new Integer[]{2130837610, 2130837612, 2130837611};
        GOD_SIX_IMAGES = arrinteger6;
        Integer[] arrinteger7 = new Integer[]{2130837592, 2130837594, 2130837593};
        GOD_SEVEN_IMAGES = arrinteger7;
        Integer[] arrinteger8 = new Integer[]{2130837555, 2130837557, 2130837556};
        GOD_EIGHT_IMAGES = arrinteger8;
        GOD_ONE_DESCRIPTION_SHORT_DESC = "Spiritual master of the world";
        GOD_TWO_DESCRIPTION_SHORT_DESC = "Remover of obstacles";
        GOD_THREE_DESCRIPTION_SHORT_DESC = "Supreme God the Protector";
        GOD_FOUR_DESCRIPTION_SHORT_DESC = "Goddess of victory of good";
        GOD_FIVE_DESCRIPTION_SHORT_DESC = "Goddess of fortune & wealth";
        GOD_SIX_DESCRIPTION_SHORT_DESC = "Indian Spiritual Satguru";
        GOD_ONE_DESCRIPTION_LONG_DESC = "Shiva also known as Mahadeva or Nataraja ,is widely known as \"the Destroyer \" or \"the Transformer \" among the Trimurti Gods, Brahma, Vishnu & Shiva.\n\nShiva has many benevolent and fearsome forms. In benevolent aspects, he is depicted as an omniscient Yogi who lives an ascetic life on Mount Kailash, with wife Parvati and his two children, Ganesha and Kartikeya. In fierce aspects, he is often depicted slaying demons. \n\nThe attributes of Shiva are the third eye on his forehead, the snake Vasuki around his neck, the crescent moon adorning, the holy river Ganga flowing from his matted hair, the Trishula as his weapon and the Damaru as his musical instrument. Shiva is usually worshiped in through the form of Shiva Lingam.";
        GOD_TWO_DESCRIPTION_LONG_DESC = "Ganesha also known as Ganapati and Vinayaka, is one of the most widely worshipped Hindu God. Ganesha has the unique distinction that his name is always invoked before any other God's name in any prayer service.\n\nLord Ganesha is the first son of Lord Shiva and Goddess Parvati and HIS elephant head makes HIM easy to identify. Ganesha is widely revered as the remover of obstacles. People do Ganesha Pooja at the start of events and ceremonies, as he is honoured as the god of beginnings. HE is widely believed to have penned the Mahabharata with his own hands.";
        GOD_THREE_DESCRIPTION_LONG_DESC = "In Hinduism, Maha Vishnu is the Supreme central God.  He is also known as Narayana and Hari. Vishnu governs the aspect of preservation and sustenance of the universe.He is called \"Preserver of the universe\" through his omnipresent characteristic (i.e. HE is present everywhere in this universe).\n\nHe has four arms and he holds a padma (lotus flower) in his lower left hand, the Kaumodaki gada (mace) in his lower right hand, the Panchajanya shankha (conch) in his upper left hand and the most powerful weapon Sudarshana Chakra in his upper right hand which rotates fast and cut off the head of enemy with its super sharp edges.\n\nVishnu the Supreme God has taken different manifest forms or avatars across various ages or periods to save humanity from evil beings, demons and Asuras. Following the defeat of Indra and his displacement as the Lord of Heaven (or Swarga), Indra asks for Lord Vishnu\u2019s help. Lord Vishnu obliges by generating himself on earth in various forms (or avatars) to save mankind, thus showing his position as Supreme God to all creations. \n\nFirst form was a water-dweller (Matsya, fish), then as an amphibious creature (Kurma avatar or Tortoise), then as a half-man-half-animal (Varaha the pig-faced), human-bodied Lord Krishna, and Narasimha the Lord with lion's face and claws and a human body). Later, Vishnu appears as human beings (Vamana the short-heighted person), Parashurama, Rama, Balarama [or Buddha according to certain schools], Krishna, and finally as Kalki (yet to form) for performing his task of protecting his devotees from demons and anti-religious entities.Out of his ten incarnations the most famous Gods are Rama and Krishna.";
        GOD_FOUR_DESCRIPTION_LONG_DESC = "Goddess Durga a manifestation of Mahashakti is also called as Adi-Parashakti & Mahisasuramardini, where shakti is the energy in the whole Universe. Durga manifested herself for the slaying the demon Mahisasura from Brahma, Vishnu, Shiva, and the lesser gods, who were otherwise powerless to overcome him. She is pure Shakti, having manifested herself within the gods so that she may fulfil the tasks of the universe via them. Durga is usually seen portrayed on top of a Lion or Tiger armed with powerful celestial weapons.\n\nAt the beginning of time, Lord Shiva invoked Durga, the primordial energy from his left half. Together they created their eternal abode, Shivaloka, also known as Kashi. As per Shiva Purana and Devi Mahatmyah, Mahishasura, the son of demon Rambha, unleashed reign of terror on earth. When gods intervened, Mahishasura defeated gods and banished them from heaven. Vanquished gods went to TriMurti- Brahma, Vishnu and Shiva. As they narrated their woeful tale, an immense mass of light manifested from Lord Vishnu's mouth, which was joined by similar rays that emerged from the enraged faces of gods. This mass of light transformed into a woman. Then all the Gods gave their divine weapon to that supreme power. Adishakti re-manifested as Durga to slay Mahishasura. Mahishasura  assumed the form of a giant elephant and tugged at Durga's lion. Durga lopped off its trunk with her sword and freed her lion. The elephant turned into a buffalo and charged at Durga. Sipping from her wine cup, Durga flung her trident and beheaded Mahishasura, finally killing him. \n\nThe four-day-long (Saptami to Dashami) Navaratri Durga Puja is the biggest annual festival in various parts of India, especially the Himalayan region, but is celebrated in various forms throughout the Hindu universe.The day of Durga's victory is celebrated as Vijayadashami, Dashain (Nepali) or Dussehra (in Hindi) \u2013 these words literally mean the Victory on the Tenth day.  ";
        GOD_FIVE_DESCRIPTION_LONG_DESC = "Shree MahaLakshmi is the Goddess of wealth and prosperity, both material and spiritual. The word \"Lakshmi\" represents the goal of life, which includes worldly as well as spiritual prosperity. Goddess Lakshmi is the wife and active energy of God Vishnu.Her four arms are symbolic of the four goals of humanity that are considered good in Hinduism \u2013 Dharma (pursuit of ethical, moral life), Artha (pursuit of wealth, means of life), Kama (pursuit of love, emotional fulfillment), and Moksha (pursuit of self-knowledge, liberation).\n\nWhen Vishnu incarnated on the Earth as the avatars Rama and Krishna, Lakshmi incarnated as his respective consorts: Sita (Rama's wife) and Rukmini (Krishna's wife). In the ancient scriptures of India, all women are declared to be embodiments of Lakshmi. \n\nIn some representations, wealth either symbolically pours out from one of her hands or she simply holds a jar of money. This symbolism has a dual meaning: wealth manifested through Lakshmi means both material as well as spiritual wealth. Lakshmi typically wears a red dress embroidered with golden threads, symbolism for beauty and wealth. She, is often represented with her husband Vishnu, the god who maintains human life filled with justice and peace. This symbolism implies wealth and prosperity is coupled with maintenance of life, justice, and peace ";
        GOD_SIX_DESCRIPTION_LONG_DESC = "Shirdi Sai Baba, was an Indian spiritual master by both his Hindu and Muslim devotees.Sai Baba is worshipped by people around the world. He had no love for perishable things and his sole concern was self-realization. He taught a moral code of love, forgiveness, helping others, charity, contentment, inner peace, and devotion to God and guru. Sai Baba's teaching combined elements of Hinduism and Islam: he gave the Hindu name Dwarakamayi to the mosque he lived in, practised Muslim rituals, taught using words and figures that drew from both traditions, and was buried in Shirdi. \n\nAccording to the book Sai Satcharita, Sai Baba arrived at the village of Shirdi in Maharashtra, when he was 16 years old. He led an ascetic life, sitting motionless under a neem tree and meditating while sitting in an asana. The people were wonder-struck to see such a young lad practising hard penance, not minding heat or cold. By day he associated with no one, by night he was afraid of nobody.His presence attracted the curiosity of the villagers, and he was regularly visited by the religiously inclined villagers. Sai Baba encouraged charity and stressed the importance of sharing.In his teachings, Sai Baba emphasised the importance of performing one's duties without attachment to earthly matters and of being content regardless of the situation. Sai Baba encouraged his devotees to pray, chant God's name. He told Muslims to study the Quran and Hindus to study texts such as the Ramayana, Bhagavad Gita, and Yoga Vasistha.\n\nSai Baba's disciples and devotees claim that he performed many miracles such as bilocation, levitation, mindreading, materialisation, exorcisms, making the river Yamuna, entering a state of Samadhi at will, lighting lamps with water, removing his limbs or intestines and sticking them back to his body (khandana yoga), curing the incurably sick, appearing beaten when another was beaten, preventing a mosque from falling down on people, and helping his devotees in a miraculous way. He also gave Darshan (vision) to people in the form of SriRama, Krishna, Vithoba and many other gods depending on the faith of devotees.According to his followers he appeared to them in dreams and gave them advice. \n\nThe Shirdi Sai movement has spread to the Caribbean and to countries such as the Nepal, Canada, United States, Australia, United Arab Emirates, Malaysia,United Kingdom, Germany, France and Singapore.He advised his devotees and followers to lead a moral life, help others, love every living being without any discrimination.";
        GOD_SEVEN_DESCRIPTION_LONG_DESC = "Krishna as the complete and eighth avatar of the God Vishnu is one of the most popular of all Hindu deities worshipped across many traditions.Krishna. is also worshipped in various names like Vasudeva, Bala Krishna or Gopala or Guruvayurappan or Kalia Mardana or Govardhana.  \n\n Krishna is often portrayed as an infant eating butter, a young boy playing a flute or as a young man along with Radha or as an elder giving direction and guidance as in the Bhagavad Gita. Lord Krishna is portrayed as a god-child, a prankster, a model lover, a divine hero, and the Supreme Being. \n\n Krishna killed the demoness Putana, disguised as a wet nurse, tamed the serpent Kaliya, who poisoned Yamuna river,leading to the death of many cows of Vrindavana. In Hindu art, Krishna is often depicted dancing on the multi-hooded Kaliya.In Bhagavat Purana, Krishna says that the rain came from the nearby hill Govardhana, and advised that the people worship the hill instead of Indra. This made Indra furious, so he punished them by sending out a great storm. Krishna then lifted Govardhan and held it over the people like an umbrella. \n\n The stories of his play with the gopis (milkmaids) of Vrindavana, especially Radha is well known as the Rasa lila which became important part of the Krishna bhakti traditions worshiping Radha Krishna. \n\n Lord Krishna is central to the main epic Mahabharath which has the Bhagavad Gita in which Krishna advises to the warrior-hero Arjuna, on the Kurukshetra battlefield.  Guruvayur temple in  Kerala, is a well known temple dedicated to Sri Krishna which attracts millions of devotees every year.";
        GOD_EIGHT_DESCRIPTION_LONG_DESC = "Ayyappan also called Sastavu, Manikandan or Sree Dharma Sastha is a Hindu deity who is born out of the union between Mohini (female avatar of Vishnu - Hari) and Shiva (Hara). Lord Ayyappa has combined in himself the powers of Lord Vishnu and Shiva. \n\n The demoness Mahishi was burning up with anger at the trick the gods had pulled on her brother, the asura king Mahishasura to kill him. Mahishi began performing a fearsome set of austerities, and pleased God Brahma. He granted her the boon of ruling the universe and being invulnerable except by the son of Shiva and Vishnu.Since such a person did not exist, she thought she was safe and began conquering and plundering the world. \n\n Ayyappa lived in the Pandalam Palace as the son / savior of the King.He had super-human , wisdom, and courage and loved the King and his people. \n He protected the King and the kingdom and killed demoness Mahishi when he was sent to forest to get the milk of Tigress to heal his mothers fake illness. \n Once he came to know the illness was fake,  when he retuned from the forest with the Tigress, he gone back to the Sabarimala forests and is ever since worshiped at the Sabarimala temple. \n\n Sabarimala in the hills of Kerala, is a well known temple dedicated for Swami Ayyapan which attracts millions of visitors every year during Nov to Jan of every year, making it one of the largest pilgrimage sites in the world.These devotees fast and engage in austerities for weeks barefoot and then travel in groups to the shrine for a glimpse of Ayyappan. The famous mantra Swamiye Saranam Ayyappa is translated in English as \"Lord Ayyappa, I seek refuge in you.\"";
        PLAY_LINK = "I am blessed to have installed \"God is with Me\" App. Pls share  with ur relatives and friends and get lot of God's blessings. https://play.google.com/store/apps/details?id=com.twinvave.godiswithme";
    }
}

